active: False

folder: no_pretrain_2_layer/eval_checkpoints

load_embeddings: False

start_layer: 0
per_component_layer_num: 2

residual: False
connect: series # series or parallel

components:
    - sst2
    - qqp
    - mrpc
    - mnli