active: False

folder: /localdisk/data2/Users/s2618109/codes/cramming/components/models
load_embeddings: True

start_layer: 0
per_component_layer_num: 2

residual: False
connect: series # series or parallel

components:
    - pos_untrain_2.safetensor