active: False

folder: /localdisk/home/s2618109/Work/Codes/Probing/models/
load_embeddings: False

start_layer: 0
per_component_layer_num: 16

residual: False # Not yet implemented
connect: series # series or parallel, Not yet implemented

components:
    - pos_untrain_16.safetensor
